[proxy]
name = "file-upload-example"
pipelines_path = "pipelines"
primary_provider = "local"

# Provider Configuration
[provider.runbeam]
api = "https://api.runbeam.cloud"
poll_interval_secs = 30

[logging]
log_level = "info"
log_to_file = true
log_file_path = "./tmp/harmony.log"

[network.default]
http.bind_address = "127.0.0.1"
http.bind_port = 8080
