[proxy]
name = "cstore-filesystem"
pipelines_path = "pipelines"
transforms_path = "transforms"
primary_provider = "local"

# Provider Configuration
[provider.runbeam]
api = "https://api.runbeam.cloud"
poll_interval_secs = 30

[logging]
log_level = "info"
log_to_file = false

# Configure the storage backend
# This determines where received DICOM files will be written.
[storage]
backend = "filesystem"
[storage.options]
path = "data"

[network.default]
enable_wireguard = false
interface = "eth0"

[network.default.tcp_config]
bind_address = "0.0.0.0"
bind_port = 11112

[services.dicom_scp]
module = ""

[services.storage]
module = ""

# ------------------------
# Peer Definitions
#-------------------------
[peers.listener_config]
connection.host = "0.0.0.0"
connection.port = 11112
connection.protocol = "dicom"
