# ------------------------
# Basic configuration
#-------------------------
[proxy]
# The name of the proxy, required
name = "harmony-dicomweb"
# The log level. Defaults to 'error'
log_level = "debug"
# Directories are resolved relative to this config file's directory
pipelines_path = "pipelines"
transforms_path = "transforms"
primary_provider = "local"

# Provider Configuration
[provider.runbeam]
api = "https://api.runbeam.cloud"
poll_interval_secs = 30

# ------------------------
# Network
#
# Defines 0 or more network configurations.
#-------------------------
[network.default]
# Whether to enable wireguard connections on this network
enable_wireguard = false
interface = "wg0"

[network.default.http]
bind_address = "0.0.0.0"  # Listen on all interfaces
bind_port = 8081          # Use port 8081

# ------------------------
# Logging
#-------------------------
[logging]
log_to_file = true
log_file_path = "./tmp/harmony_test.log"

# ------------------------
# Storage
#
# Configurable storage backend for temporary files
#-------------------------
[storage]
backend = "filesystem"

[storage.options]
path = "./tmp"

# ------------------------
# Service types
#-------------------------
[services.dicom_scu]
module=""

[services.dicomweb]
module=""

[middleware_types.dicomweb]
module=""

[middleware_types.policies]
module=""

# ------------------------
# Target Definitions
#-------------------------
[targets.orthanc]
connection.host = "localhost"
connection.port = 4242
connection.protocol = "dicom"
timeout_secs = 60
